### ISSUE TITLE
Apache changes

### ISSUE THREAD

**Issue by Saphyel** [carlosreig/docker-lamp#1]
I think you could add uploadprogress and remove vim (and maybe git as well?)

and in your php.ini I found this: date.timezone="Europe/London"
for me it's fine but I'm not sure about you :dancer: 

and why do you use this directory /var/www/html (inside the docker)?

Apologies for this wall of text and questions :( but I like it! :D nice work mate!!

**Comment by carlosreig** [comment]
Hi @Saphyel!

Thanks a lot for your feedback.

I think it's a good idea to have the uploadprogress library in the container! :) However, vim and git are programs really useful and light weighted so I think it's better to have them there.

To guess the user's timezone adds a lot of complexity compared with the value that it gives to the project IMO. But I'm open to PR :D

And I used /var/www/html because it is a quite standard directory. Do you have a better suggestion?

Thanks for the feedback again!

**Comment by Saphyel** [comment]
I think vim should be used outside and about git I guess depends of the project...

/var/www/HTML is the default but is more common use /var/www anyway this is not really important
